//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36392
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.36392 版自动生成。
// 
#pragma warning disable 1591

namespace WS.SDK.YHWxService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReservationServiceHttpEndpoint", Namespace="http://tempuri.org/")]
    public partial class ReservationService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckOutOperationCompleted;
        
        private System.Threading.SendOrPostCallback RateQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback RateQueryByCusNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReservationDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservationPaymentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReserveTypeAvailOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRmrateOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchRoomTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCusNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservationCashmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservationAccountmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCardnoConsumesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DelCardnoConsumesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservationAccountmentByCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetdicOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuestAccountQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuestOrderQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomStaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoomFutureStaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BalanceToAraccntOperationCompleted;
        
        private System.Threading.SendOrPostCallback ParamTestOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectRoomnoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSMSstateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCusnoBillOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservationPayByCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckGuestLegalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReservationService() {
            this.Url = global::WS.SDK.Properties.Settings.Default.WS_SDK_WxService_ReservationService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReservationCompletedEventHandler ReservationCompleted;
        
        /// <remarks/>
        public event CheckOutCompletedEventHandler CheckOutCompleted;
        
        /// <remarks/>
        public event RateQueryCompletedEventHandler RateQueryCompleted;
        
        /// <remarks/>
        public event RateQueryByCusNoCompletedEventHandler RateQueryByCusNoCompleted;
        
        /// <remarks/>
        public event GetReservationDetailCompletedEventHandler GetReservationDetailCompleted;
        
        /// <remarks/>
        public event ResCancelCompletedEventHandler ResCancelCompleted;
        
        /// <remarks/>
        public event ReservationPaymentCompletedEventHandler ReservationPaymentCompleted;
        
        /// <remarks/>
        public event ReserveTypeAvailCompletedEventHandler ReserveTypeAvailCompleted;
        
        /// <remarks/>
        public event GetRmrateCompletedEventHandler GetRmrateCompleted;
        
        /// <remarks/>
        public event SearchRoomTypeCompletedEventHandler SearchRoomTypeCompleted;
        
        /// <remarks/>
        public event CheckCusNoCompletedEventHandler CheckCusNoCompleted;
        
        /// <remarks/>
        public event ReservationCashmentCompletedEventHandler ReservationCashmentCompleted;
        
        /// <remarks/>
        public event ReservationAccountmentCompletedEventHandler ReservationAccountmentCompleted;
        
        /// <remarks/>
        public event GetCardnoConsumesCompletedEventHandler GetCardnoConsumesCompleted;
        
        /// <remarks/>
        public event DelCardnoConsumesCompletedEventHandler DelCardnoConsumesCompleted;
        
        /// <remarks/>
        public event ReservationAccountmentByCardCompletedEventHandler ReservationAccountmentByCardCompleted;
        
        /// <remarks/>
        public event GetdicCompletedEventHandler GetdicCompleted;
        
        /// <remarks/>
        public event GuestAccountQueryCompletedEventHandler GuestAccountQueryCompleted;
        
        /// <remarks/>
        public event GuestOrderQueryCompletedEventHandler GuestOrderQueryCompleted;
        
        /// <remarks/>
        public event GetRoomStaCompletedEventHandler GetRoomStaCompleted;
        
        /// <remarks/>
        public event GetRoomFutureStaCompletedEventHandler GetRoomFutureStaCompleted;
        
        /// <remarks/>
        public event BalanceToAraccntCompletedEventHandler BalanceToAraccntCompleted;
        
        /// <remarks/>
        public event ParamTestCompletedEventHandler ParamTestCompleted;
        
        /// <remarks/>
        public event SelectRoomnoCompletedEventHandler SelectRoomnoCompleted;
        
        /// <remarks/>
        public event GetSMSCompletedEventHandler GetSMSCompleted;
        
        /// <remarks/>
        public event UpdateSMSstateCompletedEventHandler UpdateSMSstateCompleted;
        
        /// <remarks/>
        public event GetCusnoBillCompletedEventHandler GetCusnoBillCompleted;
        
        /// <remarks/>
        public event ReservationPayByCreditCompletedEventHandler ReservationPayByCreditCompleted;
        
        /// <remarks/>
        public event CheckGuestLegalCompletedEventHandler CheckGuestLegalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/Reservation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reservation([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("Reservation", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReservationAsync(string xml) {
            this.ReservationAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReservationAsync(string xml, object userState) {
            if ((this.ReservationOperationCompleted == null)) {
                this.ReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservationOperationCompleted);
            }
            this.InvokeAsync("Reservation", new object[] {
                        xml}, this.ReservationOperationCompleted, userState);
        }
        
        private void OnReservationOperationCompleted(object arg) {
            if ((this.ReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservationCompleted(this, new ReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/CheckOut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CheckOut([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("CheckOut", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckOutAsync(string xml) {
            this.CheckOutAsync(xml, null);
        }
        
        /// <remarks/>
        public void CheckOutAsync(string xml, object userState) {
            if ((this.CheckOutOperationCompleted == null)) {
                this.CheckOutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckOutOperationCompleted);
            }
            this.InvokeAsync("CheckOut", new object[] {
                        xml}, this.CheckOutOperationCompleted, userState);
        }
        
        private void OnCheckOutOperationCompleted(object arg) {
            if ((this.CheckOutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckOutCompleted(this, new CheckOutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/RateQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RateQuery([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("RateQuery", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RateQueryAsync(string xml) {
            this.RateQueryAsync(xml, null);
        }
        
        /// <remarks/>
        public void RateQueryAsync(string xml, object userState) {
            if ((this.RateQueryOperationCompleted == null)) {
                this.RateQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRateQueryOperationCompleted);
            }
            this.InvokeAsync("RateQuery", new object[] {
                        xml}, this.RateQueryOperationCompleted, userState);
        }
        
        private void OnRateQueryOperationCompleted(object arg) {
            if ((this.RateQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RateQueryCompleted(this, new RateQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/RateQueryByCusNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RateQueryByCusNo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("RateQueryByCusNo", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RateQueryByCusNoAsync(string xml) {
            this.RateQueryByCusNoAsync(xml, null);
        }
        
        /// <remarks/>
        public void RateQueryByCusNoAsync(string xml, object userState) {
            if ((this.RateQueryByCusNoOperationCompleted == null)) {
                this.RateQueryByCusNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRateQueryByCusNoOperationCompleted);
            }
            this.InvokeAsync("RateQueryByCusNo", new object[] {
                        xml}, this.RateQueryByCusNoOperationCompleted, userState);
        }
        
        private void OnRateQueryByCusNoOperationCompleted(object arg) {
            if ((this.RateQueryByCusNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RateQueryByCusNoCompleted(this, new RateQueryByCusNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetReservationDetail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetReservationDetail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetReservationDetail", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReservationDetailAsync(string xml) {
            this.GetReservationDetailAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetReservationDetailAsync(string xml, object userState) {
            if ((this.GetReservationDetailOperationCompleted == null)) {
                this.GetReservationDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReservationDetailOperationCompleted);
            }
            this.InvokeAsync("GetReservationDetail", new object[] {
                        xml}, this.GetReservationDetailOperationCompleted, userState);
        }
        
        private void OnGetReservationDetailOperationCompleted(object arg) {
            if ((this.GetReservationDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReservationDetailCompleted(this, new GetReservationDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ResCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResCancel([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ResCancel", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ResCancelAsync(string xml) {
            this.ResCancelAsync(xml, null);
        }
        
        /// <remarks/>
        public void ResCancelAsync(string xml, object userState) {
            if ((this.ResCancelOperationCompleted == null)) {
                this.ResCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResCancelOperationCompleted);
            }
            this.InvokeAsync("ResCancel", new object[] {
                        xml}, this.ResCancelOperationCompleted, userState);
        }
        
        private void OnResCancelOperationCompleted(object arg) {
            if ((this.ResCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResCancelCompleted(this, new ResCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ReservationPayment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReservationPayment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ReservationPayment", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReservationPaymentAsync(string xml) {
            this.ReservationPaymentAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReservationPaymentAsync(string xml, object userState) {
            if ((this.ReservationPaymentOperationCompleted == null)) {
                this.ReservationPaymentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservationPaymentOperationCompleted);
            }
            this.InvokeAsync("ReservationPayment", new object[] {
                        xml}, this.ReservationPaymentOperationCompleted, userState);
        }
        
        private void OnReservationPaymentOperationCompleted(object arg) {
            if ((this.ReservationPaymentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservationPaymentCompleted(this, new ReservationPaymentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ReserveTypeAvail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReserveTypeAvail([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ReserveTypeAvail", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReserveTypeAvailAsync(string xml) {
            this.ReserveTypeAvailAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReserveTypeAvailAsync(string xml, object userState) {
            if ((this.ReserveTypeAvailOperationCompleted == null)) {
                this.ReserveTypeAvailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReserveTypeAvailOperationCompleted);
            }
            this.InvokeAsync("ReserveTypeAvail", new object[] {
                        xml}, this.ReserveTypeAvailOperationCompleted, userState);
        }
        
        private void OnReserveTypeAvailOperationCompleted(object arg) {
            if ((this.ReserveTypeAvailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReserveTypeAvailCompleted(this, new ReserveTypeAvailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetRmrate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetRmrate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetRmrate", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRmrateAsync(string xml) {
            this.GetRmrateAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetRmrateAsync(string xml, object userState) {
            if ((this.GetRmrateOperationCompleted == null)) {
                this.GetRmrateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRmrateOperationCompleted);
            }
            this.InvokeAsync("GetRmrate", new object[] {
                        xml}, this.GetRmrateOperationCompleted, userState);
        }
        
        private void OnGetRmrateOperationCompleted(object arg) {
            if ((this.GetRmrateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRmrateCompleted(this, new GetRmrateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/SearchRoomType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SearchRoomType([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("SearchRoomType", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SearchRoomTypeAsync(string xml) {
            this.SearchRoomTypeAsync(xml, null);
        }
        
        /// <remarks/>
        public void SearchRoomTypeAsync(string xml, object userState) {
            if ((this.SearchRoomTypeOperationCompleted == null)) {
                this.SearchRoomTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchRoomTypeOperationCompleted);
            }
            this.InvokeAsync("SearchRoomType", new object[] {
                        xml}, this.SearchRoomTypeOperationCompleted, userState);
        }
        
        private void OnSearchRoomTypeOperationCompleted(object arg) {
            if ((this.SearchRoomTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchRoomTypeCompleted(this, new SearchRoomTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/CheckCusNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CheckCusNo([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("CheckCusNo", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCusNoAsync(string xml) {
            this.CheckCusNoAsync(xml, null);
        }
        
        /// <remarks/>
        public void CheckCusNoAsync(string xml, object userState) {
            if ((this.CheckCusNoOperationCompleted == null)) {
                this.CheckCusNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCusNoOperationCompleted);
            }
            this.InvokeAsync("CheckCusNo", new object[] {
                        xml}, this.CheckCusNoOperationCompleted, userState);
        }
        
        private void OnCheckCusNoOperationCompleted(object arg) {
            if ((this.CheckCusNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCusNoCompleted(this, new CheckCusNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ReservationCashment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReservationCashment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ReservationCashment", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReservationCashmentAsync(string xml) {
            this.ReservationCashmentAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReservationCashmentAsync(string xml, object userState) {
            if ((this.ReservationCashmentOperationCompleted == null)) {
                this.ReservationCashmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservationCashmentOperationCompleted);
            }
            this.InvokeAsync("ReservationCashment", new object[] {
                        xml}, this.ReservationCashmentOperationCompleted, userState);
        }
        
        private void OnReservationCashmentOperationCompleted(object arg) {
            if ((this.ReservationCashmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservationCashmentCompleted(this, new ReservationCashmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ReservationAccountment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReservationAccountment([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ReservationAccountment", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReservationAccountmentAsync(string xml) {
            this.ReservationAccountmentAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReservationAccountmentAsync(string xml, object userState) {
            if ((this.ReservationAccountmentOperationCompleted == null)) {
                this.ReservationAccountmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservationAccountmentOperationCompleted);
            }
            this.InvokeAsync("ReservationAccountment", new object[] {
                        xml}, this.ReservationAccountmentOperationCompleted, userState);
        }
        
        private void OnReservationAccountmentOperationCompleted(object arg) {
            if ((this.ReservationAccountmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservationAccountmentCompleted(this, new ReservationAccountmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetCardnoConsumes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetCardnoConsumes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetCardnoConsumes", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCardnoConsumesAsync(string xml) {
            this.GetCardnoConsumesAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetCardnoConsumesAsync(string xml, object userState) {
            if ((this.GetCardnoConsumesOperationCompleted == null)) {
                this.GetCardnoConsumesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCardnoConsumesOperationCompleted);
            }
            this.InvokeAsync("GetCardnoConsumes", new object[] {
                        xml}, this.GetCardnoConsumesOperationCompleted, userState);
        }
        
        private void OnGetCardnoConsumesOperationCompleted(object arg) {
            if ((this.GetCardnoConsumesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCardnoConsumesCompleted(this, new GetCardnoConsumesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/DelCardnoConsumes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DelCardnoConsumes([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("DelCardnoConsumes", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DelCardnoConsumesAsync(string xml) {
            this.DelCardnoConsumesAsync(xml, null);
        }
        
        /// <remarks/>
        public void DelCardnoConsumesAsync(string xml, object userState) {
            if ((this.DelCardnoConsumesOperationCompleted == null)) {
                this.DelCardnoConsumesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelCardnoConsumesOperationCompleted);
            }
            this.InvokeAsync("DelCardnoConsumes", new object[] {
                        xml}, this.DelCardnoConsumesOperationCompleted, userState);
        }
        
        private void OnDelCardnoConsumesOperationCompleted(object arg) {
            if ((this.DelCardnoConsumesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DelCardnoConsumesCompleted(this, new DelCardnoConsumesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ReservationAccountmentByCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReservationAccountmentByCard([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ReservationAccountmentByCard", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReservationAccountmentByCardAsync(string xml) {
            this.ReservationAccountmentByCardAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReservationAccountmentByCardAsync(string xml, object userState) {
            if ((this.ReservationAccountmentByCardOperationCompleted == null)) {
                this.ReservationAccountmentByCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservationAccountmentByCardOperationCompleted);
            }
            this.InvokeAsync("ReservationAccountmentByCard", new object[] {
                        xml}, this.ReservationAccountmentByCardOperationCompleted, userState);
        }
        
        private void OnReservationAccountmentByCardOperationCompleted(object arg) {
            if ((this.ReservationAccountmentByCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservationAccountmentByCardCompleted(this, new ReservationAccountmentByCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/Getdic", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Getdic([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("Getdic", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetdicAsync(string xml) {
            this.GetdicAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetdicAsync(string xml, object userState) {
            if ((this.GetdicOperationCompleted == null)) {
                this.GetdicOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetdicOperationCompleted);
            }
            this.InvokeAsync("Getdic", new object[] {
                        xml}, this.GetdicOperationCompleted, userState);
        }
        
        private void OnGetdicOperationCompleted(object arg) {
            if ((this.GetdicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetdicCompleted(this, new GetdicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GuestAccountQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GuestAccountQuery([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GuestAccountQuery", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuestAccountQueryAsync(string xml) {
            this.GuestAccountQueryAsync(xml, null);
        }
        
        /// <remarks/>
        public void GuestAccountQueryAsync(string xml, object userState) {
            if ((this.GuestAccountQueryOperationCompleted == null)) {
                this.GuestAccountQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuestAccountQueryOperationCompleted);
            }
            this.InvokeAsync("GuestAccountQuery", new object[] {
                        xml}, this.GuestAccountQueryOperationCompleted, userState);
        }
        
        private void OnGuestAccountQueryOperationCompleted(object arg) {
            if ((this.GuestAccountQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuestAccountQueryCompleted(this, new GuestAccountQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GuestOrderQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GuestOrderQuery([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GuestOrderQuery", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GuestOrderQueryAsync(string xml) {
            this.GuestOrderQueryAsync(xml, null);
        }
        
        /// <remarks/>
        public void GuestOrderQueryAsync(string xml, object userState) {
            if ((this.GuestOrderQueryOperationCompleted == null)) {
                this.GuestOrderQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuestOrderQueryOperationCompleted);
            }
            this.InvokeAsync("GuestOrderQuery", new object[] {
                        xml}, this.GuestOrderQueryOperationCompleted, userState);
        }
        
        private void OnGuestOrderQueryOperationCompleted(object arg) {
            if ((this.GuestOrderQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuestOrderQueryCompleted(this, new GuestOrderQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetRoomSta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetRoomSta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetRoomSta", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomStaAsync(string xml) {
            this.GetRoomStaAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetRoomStaAsync(string xml, object userState) {
            if ((this.GetRoomStaOperationCompleted == null)) {
                this.GetRoomStaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomStaOperationCompleted);
            }
            this.InvokeAsync("GetRoomSta", new object[] {
                        xml}, this.GetRoomStaOperationCompleted, userState);
        }
        
        private void OnGetRoomStaOperationCompleted(object arg) {
            if ((this.GetRoomStaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomStaCompleted(this, new GetRoomStaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetRoomFutureSta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetRoomFutureSta([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetRoomFutureSta", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoomFutureStaAsync(string xml) {
            this.GetRoomFutureStaAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetRoomFutureStaAsync(string xml, object userState) {
            if ((this.GetRoomFutureStaOperationCompleted == null)) {
                this.GetRoomFutureStaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoomFutureStaOperationCompleted);
            }
            this.InvokeAsync("GetRoomFutureSta", new object[] {
                        xml}, this.GetRoomFutureStaOperationCompleted, userState);
        }
        
        private void OnGetRoomFutureStaOperationCompleted(object arg) {
            if ((this.GetRoomFutureStaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoomFutureStaCompleted(this, new GetRoomFutureStaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/BalanceToAraccnt", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BalanceToAraccnt([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("BalanceToAraccnt", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BalanceToAraccntAsync(string xml) {
            this.BalanceToAraccntAsync(xml, null);
        }
        
        /// <remarks/>
        public void BalanceToAraccntAsync(string xml, object userState) {
            if ((this.BalanceToAraccntOperationCompleted == null)) {
                this.BalanceToAraccntOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBalanceToAraccntOperationCompleted);
            }
            this.InvokeAsync("BalanceToAraccnt", new object[] {
                        xml}, this.BalanceToAraccntOperationCompleted, userState);
        }
        
        private void OnBalanceToAraccntOperationCompleted(object arg) {
            if ((this.BalanceToAraccntCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BalanceToAraccntCompleted(this, new BalanceToAraccntCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ParamTest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ParamTest([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ParamTest", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ParamTestAsync(string xml) {
            this.ParamTestAsync(xml, null);
        }
        
        /// <remarks/>
        public void ParamTestAsync(string xml, object userState) {
            if ((this.ParamTestOperationCompleted == null)) {
                this.ParamTestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnParamTestOperationCompleted);
            }
            this.InvokeAsync("ParamTest", new object[] {
                        xml}, this.ParamTestOperationCompleted, userState);
        }
        
        private void OnParamTestOperationCompleted(object arg) {
            if ((this.ParamTestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ParamTestCompleted(this, new ParamTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/SelectRoomno", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SelectRoomno([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("SelectRoomno", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelectRoomnoAsync(string xml) {
            this.SelectRoomnoAsync(xml, null);
        }
        
        /// <remarks/>
        public void SelectRoomnoAsync(string xml, object userState) {
            if ((this.SelectRoomnoOperationCompleted == null)) {
                this.SelectRoomnoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectRoomnoOperationCompleted);
            }
            this.InvokeAsync("SelectRoomno", new object[] {
                        xml}, this.SelectRoomnoOperationCompleted, userState);
        }
        
        private void OnSelectRoomnoOperationCompleted(object arg) {
            if ((this.SelectRoomnoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectRoomnoCompleted(this, new SelectRoomnoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetSMS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetSMS", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSMSAsync(string xml) {
            this.GetSMSAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetSMSAsync(string xml, object userState) {
            if ((this.GetSMSOperationCompleted == null)) {
                this.GetSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSMSOperationCompleted);
            }
            this.InvokeAsync("GetSMS", new object[] {
                        xml}, this.GetSMSOperationCompleted, userState);
        }
        
        private void OnGetSMSOperationCompleted(object arg) {
            if ((this.GetSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSMSCompleted(this, new GetSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/UpdateSMSstate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdateSMSstate([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("UpdateSMSstate", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSMSstateAsync(string xml) {
            this.UpdateSMSstateAsync(xml, null);
        }
        
        /// <remarks/>
        public void UpdateSMSstateAsync(string xml, object userState) {
            if ((this.UpdateSMSstateOperationCompleted == null)) {
                this.UpdateSMSstateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSMSstateOperationCompleted);
            }
            this.InvokeAsync("UpdateSMSstate", new object[] {
                        xml}, this.UpdateSMSstateOperationCompleted, userState);
        }
        
        private void OnUpdateSMSstateOperationCompleted(object arg) {
            if ((this.UpdateSMSstateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSMSstateCompleted(this, new UpdateSMSstateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/GetCusnoBill", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetCusnoBill([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("GetCusnoBill", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetCusnoBillAsync(string xml) {
            this.GetCusnoBillAsync(xml, null);
        }
        
        /// <remarks/>
        public void GetCusnoBillAsync(string xml, object userState) {
            if ((this.GetCusnoBillOperationCompleted == null)) {
                this.GetCusnoBillOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCusnoBillOperationCompleted);
            }
            this.InvokeAsync("GetCusnoBill", new object[] {
                        xml}, this.GetCusnoBillOperationCompleted, userState);
        }
        
        private void OnGetCusnoBillOperationCompleted(object arg) {
            if ((this.GetCusnoBillCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCusnoBillCompleted(this, new GetCusnoBillCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/ReservationPayByCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ReservationPayByCredit([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("ReservationPayByCredit", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReservationPayByCreditAsync(string xml) {
            this.ReservationPayByCreditAsync(xml, null);
        }
        
        /// <remarks/>
        public void ReservationPayByCreditAsync(string xml, object userState) {
            if ((this.ReservationPayByCreditOperationCompleted == null)) {
                this.ReservationPayByCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservationPayByCreditOperationCompleted);
            }
            this.InvokeAsync("ReservationPayByCredit", new object[] {
                        xml}, this.ReservationPayByCreditOperationCompleted, userState);
        }
        
        private void OnReservationPayByCreditOperationCompleted(object arg) {
            if ((this.ReservationPayByCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservationPayByCreditCompleted(this, new ReservationPayByCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IReservationService/CheckGuestLegal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CheckGuestLegal([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string xml) {
            object[] results = this.Invoke("CheckGuestLegal", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckGuestLegalAsync(string xml) {
            this.CheckGuestLegalAsync(xml, null);
        }
        
        /// <remarks/>
        public void CheckGuestLegalAsync(string xml, object userState) {
            if ((this.CheckGuestLegalOperationCompleted == null)) {
                this.CheckGuestLegalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckGuestLegalOperationCompleted);
            }
            this.InvokeAsync("CheckGuestLegal", new object[] {
                        xml}, this.CheckGuestLegalOperationCompleted, userState);
        }
        
        private void OnCheckGuestLegalOperationCompleted(object arg) {
            if ((this.CheckGuestLegalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckGuestLegalCompleted(this, new CheckGuestLegalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReservationCompletedEventHandler(object sender, ReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void CheckOutCompletedEventHandler(object sender, CheckOutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckOutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckOutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void RateQueryCompletedEventHandler(object sender, RateQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RateQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RateQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void RateQueryByCusNoCompletedEventHandler(object sender, RateQueryByCusNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RateQueryByCusNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RateQueryByCusNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetReservationDetailCompletedEventHandler(object sender, GetReservationDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReservationDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReservationDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ResCancelCompletedEventHandler(object sender, ResCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReservationPaymentCompletedEventHandler(object sender, ReservationPaymentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservationPaymentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservationPaymentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReserveTypeAvailCompletedEventHandler(object sender, ReserveTypeAvailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReserveTypeAvailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReserveTypeAvailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetRmrateCompletedEventHandler(object sender, GetRmrateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRmrateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRmrateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void SearchRoomTypeCompletedEventHandler(object sender, SearchRoomTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchRoomTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchRoomTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void CheckCusNoCompletedEventHandler(object sender, CheckCusNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCusNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCusNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReservationCashmentCompletedEventHandler(object sender, ReservationCashmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservationCashmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservationCashmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReservationAccountmentCompletedEventHandler(object sender, ReservationAccountmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservationAccountmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservationAccountmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetCardnoConsumesCompletedEventHandler(object sender, GetCardnoConsumesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCardnoConsumesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCardnoConsumesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void DelCardnoConsumesCompletedEventHandler(object sender, DelCardnoConsumesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DelCardnoConsumesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DelCardnoConsumesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReservationAccountmentByCardCompletedEventHandler(object sender, ReservationAccountmentByCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservationAccountmentByCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservationAccountmentByCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetdicCompletedEventHandler(object sender, GetdicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetdicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetdicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GuestAccountQueryCompletedEventHandler(object sender, GuestAccountQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuestAccountQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuestAccountQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GuestOrderQueryCompletedEventHandler(object sender, GuestOrderQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuestOrderQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuestOrderQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetRoomStaCompletedEventHandler(object sender, GetRoomStaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomStaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomStaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetRoomFutureStaCompletedEventHandler(object sender, GetRoomFutureStaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoomFutureStaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoomFutureStaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void BalanceToAraccntCompletedEventHandler(object sender, BalanceToAraccntCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BalanceToAraccntCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BalanceToAraccntCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ParamTestCompletedEventHandler(object sender, ParamTestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParamTestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ParamTestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void SelectRoomnoCompletedEventHandler(object sender, SelectRoomnoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectRoomnoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectRoomnoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetSMSCompletedEventHandler(object sender, GetSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void UpdateSMSstateCompletedEventHandler(object sender, UpdateSMSstateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSMSstateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSMSstateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void GetCusnoBillCompletedEventHandler(object sender, GetCusnoBillCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCusnoBillCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCusnoBillCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void ReservationPayByCreditCompletedEventHandler(object sender, ReservationPayByCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReservationPayByCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReservationPayByCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    public delegate void CheckGuestLegalCompletedEventHandler(object sender, CheckGuestLegalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.36392")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckGuestLegalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckGuestLegalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591