//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public string Code { get; set; }
        public string discount { get; set; }
        public string pic { get; set; }
        public string hotelcode { get; set; }
        public Nullable<int> px { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string ActivityName { get; set; }
        public string img { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
    }
}
