//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class categroyinfo
    {
        public string cid { get; set; }
        public string categroyid { get; set; }
        public string formulaid { get; set; }
        public Nullable<int> live { get; set; }
        public Nullable<int> weekend { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string specialtime { get; set; }
        public string hotelcode { get; set; }
    }
}
