//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class duojian_t
    {
        public int id { get; set; }
        public string hotelid { get; set; }
        public string djcode { get; set; }
        public string describe { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> money { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> type { get; set; }
    }
}
