//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetIncrease
    {
        public int id { get; set; }
        public string increase_code { get; set; }
        public string describe { get; set; }
        public string hotelid { get; set; }
        public string money { get; set; }
        public string instructions { get; set; }
        public Nullable<int> type { get; set; }
        public string flag { get; set; }
        public string roomtype { get; set; }
        public string increase { get; set; }
        public Nullable<int> px { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
    }
}
