//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetRoom
    {
        public string roomtype { get; set; }
        public string imgurl { get; set; }
        public string remark { get; set; }
        public string img { get; set; }
        public string fcode { get; set; }
        public string hotelid { get; set; }
        public string codename { get; set; }
        public string descript { get; set; }
        public string qxxz { get; set; }
        public string ydxz { get; set; }
        public int id { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> type { get; set; }
    }
}
