//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetScenceCode
    {
        public int id { get; set; }
        public string hotelid { get; set; }
        public string ratecode { get; set; }
        public string ratecodename { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> scenario { get; set; }
        public Nullable<int> type { get; set; }
        public int Expr1 { get; set; }
        public string father { get; set; }
        public string son { get; set; }
        public string yhcode { get; set; }
        public string Expr2 { get; set; }
        public int Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string yhcodename { get; set; }
        public string hotelcode { get; set; }
        public Nullable<decimal> tmoney { get; set; }
        public string Expr5 { get; set; }
        public string addname { get; set; }
        public Nullable<int> Expr6 { get; set; }
        public Nullable<int> Expr7 { get; set; }
        public int Expr8 { get; set; }
        public string Expr9 { get; set; }
        public string ratecodeorxzcode { get; set; }
        public string qudaocode { get; set; }
        public string Expr10 { get; set; }
        public string pmsratecode { get; set; }
        public int Expr11 { get; set; }
        public string Expr12 { get; set; }
        public string Expr13 { get; set; }
        public string Expr14 { get; set; }
        public string Expr15 { get; set; }
    }
}
