//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class honor
    {
        public int id { get; set; }
        public string title { get; set; }
        public string packagename { get; set; }
        public Nullable<int> FormulaId { get; set; }
        public string hotelid { get; set; }
        public Nullable<int> state { get; set; }
        public System.DateTime addtime { get; set; }
    }
}
