//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_list
    {
        public int id { get; set; }
        public string hotelId { get; set; }
        public string hotelName { get; set; }
        public string content { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> addDate { get; set; }
        public string map { get; set; }
        public string roomService { get; set; }
        public string url { get; set; }
        public string RoomTel { get; set; }
        public string RestaurantTel { get; set; }
        public string MeetingTel { get; set; }
        public string City { get; set; }
        public string HotelGroupCode { get; set; }
        public string HotelGroupName { get; set; }
        public string pms { get; set; }
        public string username { get; set; }
        public string pwd { get; set; }
        public string onsalecode { get; set; }
    }
}
