//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class increase_order
    {
        public int id { get; set; }
        public string hotelid { get; set; }
        public Nullable<int> increaseprice { get; set; }
        public string sessionid { get; set; }
        public string roomtype { get; set; }
        public string descript { get; set; }
        public Nullable<int> increasenum { get; set; }
        public Nullable<int> tian { get; set; }
        public string increasedescribe { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> ispay { get; set; }
        public Nullable<int> pay { get; set; }
        public string addtime { get; set; }
        public Nullable<int> type { get; set; }
    }
}
