//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public invoice()
        {
            this.type = 0;
            this.state = 0;
        }
    
        public int id { get; set; }
        public string Drawer { get; set; }
        public string phone { get; set; }
        public string hotelid { get; set; }
        public string hotelname { get; set; }
        public string EnterpriseName { get; set; }
        public string Taxpayer { get; set; }
        public string CreditCode { get; set; }
        public string address { get; set; }
        public string ContactNumber { get; set; }
        public string OpeningBank { get; set; }
        public string BankNumber { get; set; }
        public string InvoiceDetails { get; set; }
        public string Payment { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string bosscard { get; set; }
    }
}
