//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class yudingEntities : DbContext
    {
        public yudingEntities()
            : base("name=yudingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Activity> Activities { get; set; }
        public DbSet<associated> associateds { get; set; }
        public DbSet<baojia_t> baojia_t { get; set; }
        public DbSet<duojian_t> duojian_t { get; set; }
        public DbSet<early> earlies { get; set; }
        public DbSet<everydate_price_t> everydate_price_t { get; set; }
        public DbSet<facilities_t> facilities_t { get; set; }
        public DbSet<honor> honors { get; set; }
        public DbSet<hotelfacilities_t> hotelfacilities_t { get; set; }
        public DbSet<hotelpic_t> hotelpic_t { get; set; }
        public DbSet<increase> increases { get; set; }
        public DbSet<increase_link> increase_link { get; set; }
        public DbSet<increase_order> increase_order { get; set; }
        public DbSet<invoice> invoices { get; set; }
        public DbSet<live> lives { get; set; }
        public DbSet<log> logs { get; set; }
        public DbSet<lvyun_link> lvyun_link { get; set; }
        public DbSet<ly_order_t> ly_order_t { get; set; }
        public DbSet<ly_ratecode_link> ly_ratecode_link { get; set; }
        public DbSet<miaosha_t> miaosha_t { get; set; }
        public DbSet<newback> newbacks { get; set; }
        public DbSet<newroom_t> newroom_t { get; set; }
        public DbSet<openid> openids { get; set; }
        public DbSet<order_t> order_t { get; set; }
        public DbSet<PicClass> PicClasses { get; set; }
        public DbSet<PicDb> PicDbs { get; set; }
        public DbSet<price_formulaid> price_formulaid { get; set; }
        public DbSet<ratecode_link> ratecode_link { get; set; }
        public DbSet<ratecode_t> ratecode_t { get; set; }
        public DbSet<rateroom_xz> rateroom_xz { get; set; }
        public DbSet<room_pic_t> room_pic_t { get; set; }
        public DbSet<roomlist_ls> roomlist_ls { get; set; }
        public DbSet<roomorder_ls> roomorder_ls { get; set; }
        public DbSet<roomprice_t> roomprice_t { get; set; }
        public DbSet<roomtimestart_t> roomtimestart_t { get; set; }
        public DbSet<roomtype_f_t> roomtype_f_t { get; set; }
        public DbSet<rule> rules { get; set; }
        public DbSet<Table_1> Table_1 { get; set; }
        public DbSet<week> weeks { get; set; }
        public DbSet<xitongpic_t> xitongpic_t { get; set; }
        public DbSet<xztimestart_t> xztimestart_t { get; set; }
        public DbSet<yhcode_t> yhcode_t { get; set; }
        public DbSet<GetRoom> GetRooms { get; set; }
        public DbSet<GetScenceCode> GetScenceCodes { get; set; }
        public DbSet<View_3> View_3 { get; set; }
        public DbSet<hotel_list> hotel_list { get; set; }
        public DbSet<GetIncrease> GetIncreases { get; set; }
        public DbSet<GetRateCode_xz> GetRateCode_xz { get; set; }
        public DbSet<activity_link> activity_link { get; set; }
        public DbSet<special> specials { get; set; }
        public DbSet<newroomtime> newroomtimes { get; set; }
        public DbSet<GetRoomAndPrice> GetRoomAndPrices { get; set; }
        public DbSet<GetRateCodexzByRoomtype> GetRateCodexzByRoomtypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<hotellist> hotellists { get; set; }
        public DbSet<payurl> payurls { get; set; }
        public DbSet<categroyinfo> categroyinfoes { get; set; }
        public DbSet<categroyrule> categroyrules { get; set; }
    
        public virtual int BatchLockRoom(string xz_list, Nullable<int> islock, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var xz_listParameter = xz_list != null ?
                new ObjectParameter("xz_list", xz_list) :
                new ObjectParameter("xz_list", typeof(string));
    
            var islockParameter = islock.HasValue ?
                new ObjectParameter("islock", islock) :
                new ObjectParameter("islock", typeof(int));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BatchLockRoom", xz_listParameter, islockParameter, startParameter, endParameter);
        }
    
        public virtual ObjectResult<GetRcListByRmtype_Result> GetRcListByRmtype(string roomtype, string hotelcode, Nullable<System.DateTime> everydate)
        {
            var roomtypeParameter = roomtype != null ?
                new ObjectParameter("roomtype", roomtype) :
                new ObjectParameter("roomtype", typeof(string));
    
            var hotelcodeParameter = hotelcode != null ?
                new ObjectParameter("hotelcode", hotelcode) :
                new ObjectParameter("hotelcode", typeof(string));
    
            var everydateParameter = everydate.HasValue ?
                new ObjectParameter("everydate", everydate) :
                new ObjectParameter("everydate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRcListByRmtype_Result>("GetRcListByRmtype", roomtypeParameter, hotelcodeParameter, everydateParameter);
        }
    
        public virtual ObjectResult<GetRcListByRoomType_Result> GetRcListByRoomType(string roomtype, string hotelcode, Nullable<System.DateTime> everydate)
        {
            var roomtypeParameter = roomtype != null ?
                new ObjectParameter("roomtype", roomtype) :
                new ObjectParameter("roomtype", typeof(string));
    
            var hotelcodeParameter = hotelcode != null ?
                new ObjectParameter("hotelcode", hotelcode) :
                new ObjectParameter("hotelcode", typeof(string));
    
            var everydateParameter = everydate.HasValue ?
                new ObjectParameter("everydate", everydate) :
                new ObjectParameter("everydate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetRcListByRoomType_Result>("GetRcListByRoomType", roomtypeParameter, hotelcodeParameter, everydateParameter);
        }
    }
}
