//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPConfig
    {
        public int Id { get; set; }
        public string AppId { get; set; }
        public string AppSecret { get; set; }
        public string ShopCode { get; set; }
        public string KSHotelGroupId { get; set; }
        public string MchId { get; set; }
        public string MchKEY { get; set; }
        public string HotelName { get; set; }
        public string tenPayV3Notify { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string flag { get; set; }
        public string img { get; set; }
        public string LvyunHotelgroupId { get; set; }
        public string LvyunHotelDm { get; set; }
        public string LvyunHotelId { get; set; }
        public string LvyunHotelname { get; set; }
        public string YQTHotelgrouptype { get; set; }
        public string YQTGiftId { get; set; }
        public string YQTGiftSonId { get; set; }
        public string YQTregisterId { get; set; }
        public string YQTOperatorId { get; set; }
        public string YQTRechargeId { get; set; }
        public string YQTRechargeableId { get; set; }
        public string YQTIntegralId { get; set; }
        public string gzh { get; set; }
        public string CardId { get; set; }
        public string WxNO { get; set; }
        public string TicketImg { get; set; }
        public string FormulaImg { get; set; }
        public string TicketBgImg { get; set; }
        public string CenterImg { get; set; }
        public string AliAppid { get; set; }
        public string MerchantPrivateKey { get; set; }
        public string AlipayPublicKey { get; set; }
        public string RedirectUri { get; set; }
        public string QR { get; set; }
        public string rsvType { get; set; }
        public string orderUrl { get; set; }
        public string MerchantPublicKey { get; set; }
        public string src { get; set; }
        public string market { get; set; }
        public string Qy { get; set; }
    }
}
