//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class newback
    {
        public int id { get; set; }
        public string hotelid { get; set; }
        public string oid { get; set; }
        public string type { get; set; }
        public string yemian { get; set; }
        public string operation { get; set; }
        public string olddata { get; set; }
        public string newdata { get; set; }
        public string addtime { get; set; }
    }
}
