//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class newroom_t
    {
        public newroom_t()
        {
            this.flag = 0;
            this.islock = 0;
            this.img = "pic.jpg";
        }
    
        public int id { get; set; }
        public string hotelid { get; set; }
        public string roomtype { get; set; }
        public string descript { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public Nullable<int> pxid { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> islock { get; set; }
        public Nullable<int> num { get; set; }
        public string img { get; set; }
        public string remark { get; set; }
        public string yuanjia { get; set; }
        public Nullable<int> type { get; set; }
        public string twxq { get; set; }
        public string pms { get; set; }
        public string state { get; set; }
        public string qxxz { get; set; }
        public string ydxz { get; set; }
        public string qudao { get; set; }
        public string pmsratecode { get; set; }
    }
}
