//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class rateroom_xz
    {
        public rateroom_xz()
        {
            this.flag = 0;
            this.state = "0";
            this.istime = 0;
        }
    
        public int id { get; set; }
        public string xz_code { get; set; }
        public string xz_name { get; set; }
        public string hotelid { get; set; }
        public string roomtype { get; set; }
        public string roomtypename { get; set; }
        public string ratecode { get; set; }
        public string ratecodename { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> package { get; set; }
        public Nullable<int> pay { get; set; }
        public int flag { get; set; }
        public string ydxz { get; set; }
        public string qxxz { get; set; }
        public Nullable<int> px { get; set; }
        public string mubancode { get; set; }
        public Nullable<int> duojian { get; set; }
        public Nullable<int> WeekIndex { get; set; }
        public string qudao { get; set; }
        public string pmsratecode { get; set; }
        public string payway { get; set; }
        public string state { get; set; }
        public Nullable<int> istime { get; set; }
        public Nullable<int> chaifen { get; set; }
        public string cusno { get; set; }
        public string onsalecode { get; set; }
    }
}
