//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomorder_ls
    {
        public int id { get; set; }
        public string hotelcode { get; set; }
        public string roomtype { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public string useraccount { get; set; }
        public string session { get; set; }
        public string cardno { get; set; }
        public Nullable<System.DateTime> starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public string ratecode { get; set; }
        public string rate { get; set; }
        public string roomname { get; set; }
        public string trueRate { get; set; }
    }
}
