//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class special
    {
        public special()
        {
            this.minutes = 30;
            this.bgimg = "hyrz.jpg";
            this.isname = "0";
            this.isRecommend = "0";
            this.isSendWeather = "0";
        }
    
        public int id { get; set; }
        public string operation { get; set; }
        public Nullable<int> minutes { get; set; }
        public string bgimg { get; set; }
        public string isname { get; set; }
        public Nullable<int> type { get; set; }
        public string hotelcode { get; set; }
        public string isRecommend { get; set; }
        public string isSendWeather { get; set; }
    }
}
