//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yuding.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_3
    {
        public string startdate { get; set; }
        public string enddate { get; set; }
        public string starttime { get; set; }
        public string endtime { get; set; }
        public string week { get; set; }
        public Nullable<int> flag { get; set; }
        public string batch { get; set; }
        public Nullable<int> px { get; set; }
        public string hotelid { get; set; }
        public int id { get; set; }
        public string pms { get; set; }
        public Nullable<int> type { get; set; }
        public string yuanjia { get; set; }
        public string remark { get; set; }
        public string img { get; set; }
        public Nullable<int> num { get; set; }
        public Nullable<int> islock { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<int> pxid { get; set; }
        public string addtime { get; set; }
        public string descript { get; set; }
        public string Expr3 { get; set; }
    }
}
